### ISSUE TITLE
`swarm format` through `stdin`

### ISSUE THREAD

**Issue by RustemB** [byorgey/swarm#140]
Format through `stdin` to use in some programs, like in `efm-langserv` https://github.com/mattn/efm-langserver
like so
```yaml
swarm: &swarm
    format-command: 'swarm format -'
    format-stdin: true
```
